### ISSUE TITLE
"Custom_Dataset" Notebook shows no performance improvement across epochs

### ISSUE THREAD

**Issue by sachinmotwani20** [microsoft/Semi-supervised-learning#104]
## Bug

When run, the custom example notebook does not demonstrate the algorithm is learning. The output is the same across epochs. The same problem, when faced in beginner_notebook was resolved using the following (https://github.com/sachinmotwani20/semilearn/blob/36e5a23bca9c584a03083f11dbb22a1104f4b1a2/Beginner_example/Beginner_Example.py):
```
algorithm.model = algorithm.model.cuda()
algorithm.train()
algorithm.evaluate()
```

But this did not work for the custom_dataset notebook.

### Error Messages and Logs 

Output:

> Epoch: 0
> [2023-05-12 11:27:21,704 INFO] confusion matrix
> [2023-05-12 11:27:21,705 INFO] [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
> [2023-05-12 11:27:21,709 INFO] evaluation metric
> [2023-05-12 11:27:21,710 INFO] acc: 0.1002
> [2023-05-12 11:27:21,711 INFO] precision: 0.0100
> [2023-05-12 11:27:21,711 INFO] recall: 0.1000
> [2023-05-12 11:27:21,712 INFO] f1: 0.0182
> Epoch: 1
> [2023-05-12 11:27:31,597 INFO] confusion matrix
> [2023-05-12 11:27:31,598 INFO] [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
> [2023-05-12 11:27:31,601 INFO] evaluation metric
> [2023-05-12 11:27:31,601 INFO] acc: 0.1002
> [2023-05-12 11:27:31,602 INFO] precision: 0.0100
> [2023-05-12 11:27:31,602 INFO] recall: 0.1000
> [2023-05-12 11:27:31,603 INFO] f1: 0.0182
> Epoch: 2
> [2023-05-12 11:27:41,428 INFO] confusion matrix
> [2023-05-12 11:27:41,429 INFO] [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
> [2023-05-12 11:27:41,433 INFO] evaluation metric
> [2023-05-12 11:27:41,434 INFO] acc: 0.1002
> [2023-05-12 11:27:41,434 INFO] precision: 0.0100
> [2023-05-12 11:27:41,435 INFO] recall: 0.1000
> [2023-05-12 11:27:41,435 INFO] f1: 0.0182
> ...
> Epoch: 29
> [2023-05-12 11:32:13,598 INFO] confusion matrix
> [2023-05-12 11:32:13,599 INFO] [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
> [2023-05-12 11:32:13,602 INFO] evaluation metric
> [2023-05-12 11:32:13,602 INFO] acc: 0.1002
> [2023-05-12 11:32:13,603 INFO] precision: 0.0100
> [2023-05-12 11:32:13,603 INFO] recall: 0.1000
> [2023-05-12 11:32:13,604 INFO] f1: 0.0182
> [2023-05-12 11:32:13,685 INFO] Best acc 0.1002 at epoch 0
> [2023-05-12 11:32:13,685 INFO] Training finished.
> [2023-05-12 11:32:15,855 INFO] confusion matrix
> [2023-05-12 11:32:15,856 INFO] [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
> [2023-05-12 11:32:15,859 INFO] evaluation metric
> [2023-05-12 11:32:15,859 INFO] acc: 0.1002
> [2023-05-12 11:32:15,860 INFO] precision: 0.0100
> [2023-05-12 11:32:15,860 INFO] recall: 0.1000
> [2023-05-12 11:32:15,860 INFO] f1: 0.0182

Moreover, when the below code is used,
```
algorithm.model = algorithm.model.cuda()
algorithm.train()
```
it produces the following error.

> AttributeError: 'NoneType' object has no attribute 'items'

Could someone please tell me why no learning happens? 
I have not changed anything in the notebook except the number of epochs.

**Comment by Hhhhhhao** [comment]
Possibly the same reason as #74

**Comment by sachinmotwani20** [comment]
But #74 was resolved using the code 
`algorithm.model = algorithm.model.cuda()
algorithm.train()
algorithm.evaluate()`

This is not the case here.
