### ISSUE TITLE
multiprocessing error

### ISSUE THREAD

**Issue by Re-dot-art** [microsoft/Semi-supervised-learning#107]
## Bug
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV

I use the python=3.8. and install the module dependency: pip install -r requirements.txt
Then, python3 train.py --c config/usb_cv/freematch/freematch_cifar100_100_200_0.yaml

I get the error: torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV

**Comment by Hhhhhhao** [comment]
This might be a package version error. Try to upgrade Pytorch and Transformers. Let me know if this problem still come up.
