### ISSUE TITLE
Adding pretrained weight for Resnet model.

### ISSUE THREAD

**Issue by opencomvis** [microsoft/Semi-supervised-learning#112]
Thanks for your great work!
*Is there any pretrained weights for ResNet50?*
The model exists under nets folder, however, it seems that it doesn't support pretrained weights. 
Therefore, firstly, I have amend this modification to the model:

```
def resnet50(pretrained=False, pretrained_path=None, **kwargs):
    model = ResNet50(**kwargs)
    if pretrained:
        model = load_checkpoint(model, pretrained_path)   
    return model
```

Then, I have proposed to use the following example pretrained weight of ResNet50: 
https://download.pytorch.org/models/resnet50-11ad3fa6.pth

Could you please confirm that these modification are correct? 
since ResNet50 is widely used as a backbone in previous semi-supervised learning algorithms, I am interested in test it out.
Thank you.

**Comment by Hhhhhhao** [comment]
The modification seems correctly. You have to debug the code to make sure the pretrained checkpoint you want is successfully loaded.
