### ISSUE TITLE
Adding DeFixmatch in USB

### ISSUE THREAD

**Issue by HugoSchmutz** [microsoft/Semi-supervised-learning#116]
Hi,

During ICLR 2023, I discussed with Yue Fan the possibility of adding a new method named DeFixmatch in the USB repo.
Check out the paper here: https://arxiv.org/pdf/2203.07512.pdf

The idea of this paper is to debiased the estimator using labelled data to provide simple theoretical guarantees to most deep SSL methods without degradation of performance.  In particular, we applied it successfully on Fixmatch, namely DeFixmatch.

I modified the code of USB to integrate DeFixmatch and we test it on the computer vision benchmark. DeFixmatch reached the best performance on 4 tasks. I wanted to propose to you and discuss with you the possibility of adding the method to the repo. 

Best,
Hugo

**Comment by Hhhhhhao** [comment]
Hi Hugo,

I've known your method since summer last year. It would be great if we could integrate it into USB. 
I would suggest we open a new branch and a pull request for this update. And it will be integrated into main branch in July or Aug. 

Best,
Hao.

**Comment by HugoSchmutz** [comment]
Nice! Good to hear :)

Ok, I am creating the new branch. 
Do you need us to run the full benchmark to fill the results section? 

Best,
Hugo

**Comment by Hhhhhhao** [comment]
I think results with WRN would be fine for now. We will verify the remaining ones.

**Comment by Hhhhhhao** [comment]
> Ok perfect.
> 
> Quick remark: line 71 of semilearn/datasets/collactors/audio_collactor.py, I think it should be 'label' and not 'labels' as 'labels' can never been in the batches defined in semilearn/datasets/audio_datasets/datasetbase.py.

Thanks! This might be a typo. Will fix it :)

**Comment by HugoSchmutz** [comment]
Well, it was not a typo. My bad. it should be 'labels' as it is defined in the PreTrainedTokenizerBase object from huggingface.
We are almost ready to propose the pull request. We are finishing to run the computer vision benchmark. 
We will run the audio and nlp benchmarks soon

**Comment by Hhhhhhao** [comment]
Merged in https://github.com/microsoft/Semi-supervised-learning/pull/129.
