### ISSUE TITLE
Obtain hyperparameters for displaying results

### ISSUE THREAD

**Issue by Re-dot-art** [microsoft/Semi-supervised-learning#118]
I want to know what hyperparameters were used to run the results you posted on Github. Specific links: https://github.com/microsoft/Semi-supervised-learning/blob/main/results/usb_cv.csv     
Is the result of running the. yaml file in Github ./config/usb_cv?  But there is a question that the hyperparameter settings in these files, such as batch size, the batch size is 8 in .yaml file, do not match those in the USB paper that is 16. Which should I follow to run them ?

**Comment by Hhhhhhao** [comment]
We use batch size 8 for the new results updated later. You can check the training parameters in the log files to verify that.

**Comment by Re-dot-art** [comment]
> We use batch size 8 for the new results updated later. You can check the training parameters in the log files to verify that.

![image](https://github.com/microsoft/Semi-supervised-learning/assets/93500522/43729327-8396-4da9-ab42-b049a161be63)
Is the result currently visible running with batch size=8? I can't find the log file you mentioned.

**Comment by Hhhhhhao** [comment]
Logs files are here: https://drive.google.com/drive/folders/1bRSqrRyyuDafgOI3VAuqqiuzHG6CexHF
