### ISSUE TITLE
[Question / Suggestion] Potential bug in the sample_labeled_unlabeled_data.

### ISSUE THREAD

**Issue by bhoo-git** [microsoft/Semi-supervised-learning#119]
## Bug
 
`algorithm = get_algorithm(config,  get_net_builder(config.net, from_name=False), tb_log=None, logger=None)`

Running the following cell in step 2 of the Beginner_Example.ipynb notebook returns the following error: 

`TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'`. Here is a screenshot of the actual error message.

![Screenshot 2023-06-28 113633](https://github.com/microsoft/Semi-supervised-learning/assets/112581448/16eebb47-b585-4fd4-902e-6e853ae2e344)

I believe this is because of the if statement in line 83 of the sample_labeled_unlabeled_data function in semilearn/datasets/utils.py. 

![error](https://github.com/microsoft/Semi-supervised-learning/assets/112581448/722dbbb3-702e-4ae4-b1e8-bce11b50881f)

The default value for the variable `ulb_num_labels` is `None` (Nonetype), but the second half of the if statement returns `True` because `None != "None"` is true due to the string-NoneType type difference. 

I found that this issue can be resolved by breaking the two if statements into separate lines as below:

![Screenshot 2023-06-28 114342](https://github.com/microsoft/Semi-supervised-learning/assets/112581448/274d0f75-e52e-4f2b-b87e-84eba03c67af)

### Reproduce the Bug

Python version: 3.7.16
Dependencies: installed using `pip install -r requirements.txt` after cloning the github repo.

### Error Messages and Logs

Provided above.

**Comment by Hhhhhhao** [comment]
Thanks for reporting this bug. 
Would simply replace the or operation with and operation resolve the problem?
Or more strictly, we can add constraints in arguments to prevent the ```ulb_num_labels``` to be string type.

**Comment by Hhhhhhao** [comment]
Fixed in PR #135
