### ISSUE TITLE
Cannot install 0.3.0 version and Colab examples are failed to run

### ISSUE THREAD

**Issue by alysia2019** [microsoft/Semi-supervised-learning#120]
1. try to run pip install semilearn==0.3.0 but 0.2.4 downloaded instead, not sure if that is correct.

2. the Colab example "Custom_Dataset.ipynb" is failed to run as NotImplementedError raised after defining configs and creating config

Can anyone help with these issues?

**Comment by Hhhhhhao** [comment]
I found this is due to mkl-fft==1.3.0 previously in requirements.txt has no longer correct version in pip. I have already updated this requirement. But to use 0.3.0, you have to install from source now:

```
git clone https://github.com/microsoft/Semi-supervised-learning.git
pip install -e ./
```

**Comment by alysia2019** [comment]
> 

Thank you sooo much, I will give it a try and see how it looks.

**Comment by alysia2019** [comment]
> I found this is due to mkl-fft==1.3.0 previously in requirements.txt has no longer correct version in pip. I have already updated this in requirement (#122). But to use 0.3.0, you have to install from source now:
> 
> ```
> git clone https://github.com/microsoft/Semi-supervised-learning.git
> pip install -e ./
> ```

Thank you so much for the prompt reply. but unfortunately, mkl-fft>=1.3.0 will still raise an error in colab. I think  mkl-fft might unnecessary?

and I also find that semilearn 0.3.0 is incompatible with Apple M1 chip, specifically for the tensorflow-macos. and mkt is not available in Apple M1 

I guess it would be possible to loosen the version requirements.

**Comment by ZahraaHM** [comment]
I have the same problem , it is not resolved for sorry

**Comment by Hhhhhhao** [comment]
> I have the same problem , it is not resolved for sorry

Have you tried to install the latest semilearn==0.3.1? This problem should be addressed in the new version.

**Comment by ZahraaHM** [comment]
yes, I used the last version linked in README, just with last two hours
![image](https://github.com/microsoft/Semi-supervised-learning/assets/36459979/3a8a8b4a-0564-4c14-9cab-5c020b826365)

**Comment by Hhhhhhao** [comment]
> yes, I used the last version linked in README, just with last two hours ![image](https://user-images.githubusercontent.com/36459979/260880846-3a8a8b4a-0564-4c14-9cab-5c020b826365.png)

I see. This might be caused by the update on the colab side. If you create a new conda environment and install semilearn, there won't be any problem:
![image](https://github.com/microsoft/Semi-supervised-learning/assets/39571115/795f315b-e3e5-4683-91ea-ee6b9fc9b251)

```
conda create -n test_semilearn python=3.10
conda activate test_semilearn
pip install -U semilearn==0.3.1
```
