### ISSUE TITLE
Custom_Dataset example - AttributeError: 'Namespace' object has no attribute 'amp'

### ISSUE THREAD

**Issue by alysia2019** [microsoft/Semi-supervised-learning#123]
I tried to run the example Custom_Dataset.ipynb (https://colab.research.google.com/drive/1zbswPm1sM8j0fndUQOeqX2HADdYq-wOw) but an error raised:

in FixMatch.__init__(self, args, net_builder, tb_log, logger)
     33 def __init__(self, args, net_builder, tb_log=None, logger=None):
---> 34     super().__init__(args, net_builder, tb_log, logger) 
     35     # fixmatch specified arguments
     36     self.init(T=args.T, p_cutoff=args.p_cutoff, hard_label=args.hard_label)
...
---> 54 self.use_amp = args.amp
     55 self.clip_grad = args.clip_grad
     56 self.save_name = args.save_name

AttributeError: 'Namespace' object has no attribute 'amp'

This bug should be fixed before but I am pretty sure that I've downloaded the latest version of the package.

Can anyone help with this error?

**Comment by zhaisilong** [comment]
try this `self.use_amp = args.use_amp`
