### ISSUE TITLE
Questions: is "num_labels" for defining the number of labeled instances?

### ISSUE THREAD

**Issue by alysia2019** [microsoft/Semi-supervised-learning#124]
I tried to understand the config in Custom_Dataset.ipynb (https://colab.research.google.com/drive/1zbswPm1sM8j0fndUQOeqX2HADdYq-wOw#scrollTo=AtcX_BjIcOEp) and went through the tutorial but didn't find an explanation of num_labels, can anyone please give me a hint?

**Comment by alysia2019** [comment]
I reviewed some papers and find some papers has very vague description regarding the number of labels they used. One paper clearly states that the number of labels means the labelled data size, so I assume it has the same meaning here. Please point out if I was wrong.

**Comment by Hhhhhhao** [comment]
```num_labels``` means the number of labels in labeled dataset

**Comment by alysia2019** [comment]
> `num_labels` means the number of labels in labeled dataset

Thank you soooo much.
