### ISSUE TITLE
where is "model.train()" in "Semi-supervised-learning/train.py line 282"

### ISSUE THREAD

**Issue by lwj1234** [microsoft/Semi-supervised-learning#127]
I want to learn the process of training,but can't find the function "model.train()"，I know it is related to the model you selected, so how do I find this function

**Comment by Hhhhhhao** [comment]
Try to 'Ctrl + F' search for ```model.train()```, you will easily find it appears in both train function and evaluation function :).

**Comment by lwj1234** [comment]
Thank you very much for your help! I have found it in “semilearn/core/algorithmbase.py”！
