### ISSUE TITLE
关于多进程分布式的训练参数

### ISSUE THREAD

**Issue by lwj1234** [microsoft/Semi-supervised-learning#130]
嗨，我遇到了以下问题需要帮助！
我使用的配置文件（未做任何修改）：config/classic_cv/freematch/freematch_cifar10_40_0.yaml
我运行的命令：python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml
加速卡Tesla V100-SXM2-32GB：2个
CPU：20

我的问题：
1、freematch_cifar10_40_0.yaml文件中num_workers=1，这个参数是用来加载数据的吗？是否可以设置大一点？设置大一点会训练快一点吗
2、freematch_cifar10_40_0.yaml文件中的world_size=1代表Number of nodes，rank=0代表node rank，我是单机多卡，这两个参数是不是不用改了
3、freematch_cifar10_40_0.yaml文件中seed=0，为什么要设置seed=0，而且训练时，有关于seed的警告：
train.py:185: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
为什么设置了seed会大大减慢训练速度呢？可以设置为none或者别的数字吗？
4、freematch_cifar10_40_0.yaml文件中num_train_iter=1048576，cifar10数据集不是很大，为什么要设置这么大的iter，我运行python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml，12个多小时才训练到25万左右的iter，复现的时间成本太大了。
5、我在train.py main_worker函数中print了一些参数，能证明main_worker确实被调用了两次，说明有两个进程，但是logger.info(f"UseGPU:{args.gpu}fortraining")这个命令只输出了Use GPU: 0 for training，为什么没有输出Use GPU: 1 for training呢？我使用watch nvidia-smi看gpu利用率，发现两个gpu都在工作。
使用多进程分布式训练是否还需要别的参数设置呢？我未修改配置文件，执行python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml命令，现在我不确定是否两个gpu都在同时训练。
命令行的一些输出：
ngpus_per_node 2
gpu 1
rank 1
args.world_size 2
gpu 0
rank 0
args.world_size 2
[2023-07-12 05:00:17,193 INFO] Use GPU: 0 for training
6、怎么能减少复现的时间成本，训练慢的原因在哪

对于您的帮助非常感谢！！！

**Comment by lwj1234** [comment]
logger_level = "WARNING"
    tb_log = None
    if args.rank % ngpus_per_node == 0:
        tb_log = TBLog(save_path, 'tensorboard', use_tensorboard=args.use_tensorboard)
        logger_level = "INFO"

    logger = get_logger(args.save_name, save_path, logger_level)
    logger.info(f"Use GPU: {args.gpu} for training")
 
多进程分布式训练不需要修改什么参数，直接执行python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml，在train.py中会自动根据gpu的数量确定进程的数量，之所以只输出了 Use GPU: 0 for training，是因为只有args.rank % ngpus_per_node == 0的进程的logger_level是INFO，会输出logger.info(f"UseGPU:{args.gpu}fortraining"）命令。其他rank的logger_level是WARNING，不执行logger.info(f"UseGPU:{args.gpu}fortraining"）。可以看train.py244-251行。所以在单机多卡的情况下，只要配置为文件中multiprocessing_distributed: True，就会启动多进程分布式训练。

**Comment by Hhhhhhao** [comment]
> 嗨，我遇到了以下问题需要帮助！ 我使用的配置文件（未做任何修改）：config/classic_cv/freematch/freematch_cifar10_40_0.yaml 我运行的命令：python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml 加速卡Tesla V100-SXM2-32GB：2个 CPU：20
> 
> 我的问题： 1、freematch_cifar10_40_0.yaml文件中num_workers=1，这个参数是用来加载数据的吗？是否可以设置大一点？设置大一点会训练快一点吗 2、freematch_cifar10_40_0.yaml文件中的world_size=1代表Number of nodes，rank=0代表node rank，我是单机多卡，这两个参数是不是不用改了 3、freematch_cifar10_40_0.yaml文件中seed=0，为什么要设置seed=0，而且训练时，有关于seed的警告： train.py:185: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints. warnings.warn('You have chosen to seed training. ' 为什么设置了seed会大大减慢训练速度呢？可以设置为none或者别的数字吗？ 4、freematch_cifar10_40_0.yaml文件中num_train_iter=1048576，cifar10数据集不是很大，为什么要设置这么大的iter，我运行python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml，12个多小时才训练到25万左右的iter，复现的时间成本太大了。 5、我在train.py main_worker函数中print了一些参数，能证明main_worker确实被调用了两次，说明有两个进程，但是logger.info(f"UseGPU:{args.gpu}fortraining")这个命令只输出了Use GPU: 0 for training，为什么没有输出Use GPU: 1 for training呢？我使用watch nvidia-smi看gpu利用率，发现两个gpu都在工作。 使用多进程分布式训练是否还需要别的参数设置呢？我未修改配置文件，执行python train.py --c config/classic_cv/freematch/freematch_cifar10_40_0.yaml命令，现在我不确定是否两个gpu都在同时训练。 命令行的一些输出： ngpus_per_node 2 gpu 1 rank 1 args.world_size 2 gpu 0 rank 0 args.world_size 2 [2023-07-12 05:00:17,193 INFO] Use GPU: 0 for training 6、怎么能减少复现的时间成本，训练慢的原因在哪
> 
> 对于您的帮助非常感谢！！！

Hi, I find the answers for most of your questions are covered in our paper, please refer them again for your concern.

1. num_workers will change the speed of loading data. if you observe the data time in logging is very slow, try to adjust this parameter.
2. As you mentioned in your reply, this number doesn't need any change.
3. Setting seed is for reproducible results. Google "CUDNN deterministic setting" and you will find the reason for the warning.
4. Please refer to USB paper.
5. As you mentioned in your reply, if you do not set ```CUDA_VISIBLE_DEVICES``` manually, the process will use all GPUs by default.
6. Please refer to USB paper.

**Comment by lwj1234** [comment]
You are very kind. Thank you very much for your reply. I will carefully review the paper.

**Comment by lwj1234** [comment]
嗨，我一开始看的是FreeMatch论文，在第五章节中，论文提到使用的是TorchSSL和resnet对所有算法进行评估，所以我选择了config/classic_cv/freematch/freematch_cifar10_40_0.yaml 配置文件，根据你的建议我看了USB论文，现在明白了：config/classic_cv 使用的resnet，基于TorchSSL，是从头开始训练ResNet。而 config/usb_cv 使用 vi，基于USB，是使用预训练的Transformers。所以我应该使用 config/usb_cv 下的配置文件，这样训练会快一点。
但是config/usb_cv/Freematch 下没有使用cifar10的配置文件，只有cifar100。

**Comment by lwj1234** [comment]
还有一个问题，不管使用config/classic_cv还是config/usb_cv 中的配置文件，是不是只有配置文件中某些参数不同，比如net，epoch等，但是它们训练的流程是一致的，就是说我看了配置文件以后，再去看train.py，再去看semilearn/core/algorithmbase.py，最后再去看semilearn/algorithms/freematch/freematch.py，类 FreeMatch继承了类AlgorithmBase。按照这个顺序看我应该能清楚整个训练过程吧

**Comment by lwj1234** [comment]
在config/classic_cv/freematch/freematch_cifar10_40_0.yaml配置文件中，batch_size: 64，但是总共只有40个标注样本，get_data_loader时怎么凑出64个样本呢？

**Comment by lwj1234** [comment]
现在我使用config/usb_cv/freematch/freematch_cifar100_400_0.yaml，基于usb的配置文件。
1、运行时发现加速卡显存利用率比较低，增大batch size后，加速卡显存利用率明显增加，加速卡利用率也会增加，但是训练速度好像更慢了，相邻两次log结果的时间变长了。会不会是因为，每个itetation的batch size增大了，计算时间增加，所以每256个iteration打印一次，相邻两次打印时间间隔更长，训练到最后204800个iter的时间会更长。难道我增大batch size的时候需要相应减小num_train_iter？
2、epoch和iteration要满足倍数关系，这个倍数关系代表每个epoch包括多少iteration。那batch size和这两个参数什么关系呢？好像也不满足 one epoch（训练样本总数）=batch size×num_iter_per_epoch，num_iter_per_epoch=204800÷200=1024
下面时配置文件部分参数：
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 16
uratio: 1
num_workers: 4

**Comment by lwj1234** [comment]
非常感谢你的帮助！以后不会再这么多问题占用您的时间! :)

**Comment by lwj1234** [comment]
@Hhhhhhao

**Comment by lwj1234** [comment]
@Hhhhhhao 是不是每个epoch不需要利用完全部的训练数据

**Comment by Hhhhhhao** [comment]
> 现在我使用config/usb_cv/freematch/freematch_cifar100_400_0.yaml，基于usb的配置文件。 1、运行时发现加速卡显存利用率比较低，增大batch size后，加速卡显存利用率明显增加，加速卡利用率也会增加，但是训练速度好像更慢了，相邻两次log结果的时间变长了。会不会是因为，每个itetation的batch size增大了，计算时间增加，所以每256个iteration打印一次，相邻两次打印时间间隔更长，训练到最后204800个iter的时间会更长。难道我增大batch size的时候需要相应减小num_train_iter？ 2、epoch和iteration要满足倍数关系，这个倍数关系代表每个epoch包括多少iteration。那batch size和这两个参数什么关系呢？好像也不满足 one epoch（训练样本总数）=batch size×num_iter_per_epoch，num_iter_per_epoch=204800÷200=1024 下面时配置文件部分参数： epoch: 200 num_train_iter: 204800 num_log_iter: 256 num_eval_iter: 2048 batch_size: 8 eval_batch_size: 16 uratio: 1 num_workers: 4

Most of your questions can be answered from paper and code. Please read the code carefully again for sampling the data. 
For the batch size, we fixed the batch size and training iteration for fair comparison of each algorithms. You can set them to any number. Larger batch size would increase the time for each training iteration.

**Comment by lwj1234** [comment]
Thank you very much for all your help! Wishing you all the best.:）
