### ISSUE TITLE
怎么找到softmatch全文的代码

### ISSUE THREAD

**Issue by 18637838358** [microsoft/Semi-supervised-learning#132]
您好 看了您的工作感觉很棒，对我很受启发，但是只在semilearn中找到了softmatch定义部分的代码，想学习这篇文章全文的代码，哪里可以找到呢？期待您的回复，不胜感激！

**Comment by Hhhhhhao** [comment]
Hi, we use the code in semilearn to run all experiments in SoftMatch paper, so this is the code for softmatch.

**Comment by 18637838358** [comment]
好的 感谢您的回复 。由于学生才入门不久，理解的不够透彻，您觉得文章中softmach改进伪标签的代码可以直接适用于半监督脑电信号数据分类中吗？代码中有两个无标签样本 x_ulb_w 和 x_ulb_s，是分别通过强弱增强产生的吗？这是针对图像识别的增强，不知道我的脑电信号数据是否适用

**Comment by Hhhhhhao** [comment]
> 好的 感谢您的回复 。由于学生才入门不久，理解的不够透彻，您觉得文章中softmach改进伪标签的代码可以直接适用于半监督脑电信号数据分类中吗？代码中有两个无标签样本 x_ulb_w 和 x_ulb_s，是分别通过强弱增强产生的吗？这是针对图像识别的增强，不知道我的脑电信号数据是否适用

I think changing to EEG-specific augmentation would be more reasonable.

**Comment by 18637838358** [comment]
您好 您觉得softmax方法适合于小数据集吗，比如在迁移学习模型中训练集2000个有标签样本，测试集250个无标签样本？在考虑无标签样本太少只有250个，通过该方法改进伪标签提升效果会不会不好。期待您的回复，感谢！

**Comment by Hhhhhhao** [comment]
Most semi-supervised learning methods requires the unlabeled set to be much larger than the labeled set, otherwise the performance cannot get guranteed.

**Comment by Swww-w** [comment]
> 您好 看了您的工作感觉很棒，对我很受启发，但是只在semilearn中找到了softmatch定义部分的代码，想学习这篇文章全文的代码，哪里可以找到呢？期待您的回复，不胜感激！

您好 ， 本人纯小白 想知道 ，大佬您是如何用这个框架的 ，是在Linux虚拟机上使用这个框架还是咋用的，期待您的回复，感谢！
