### ISSUE TITLE
random seeds

### ISSUE THREAD

**Issue by weiling666** [microsoft/Semi-supervised-learning#138]
Thank you very much for your work.  In the usb_cv results, I found that the differences in experimental results were a little big. fixmatch: 29.6+0.9 flexmatch:26.76+1.12, but random seeds had been fixed in the experimental code, why were there still big differences in the results after random seeds had been fixed, or no random seeds were fixed in the experiment?

**Comment by Hhhhhhao** [comment]
All experiments/benchmark results are running with fixed random seed.

**Comment by weiling666** [comment]
Thank you for your research and your response

**Comment by mezbaur-rahman** [comment]
What are the different random seeds used for the experiments other than 0?
