### ISSUE TITLE
NLP datasets download link

### ISSUE THREAD

**Issue by qfkkwgd** [microsoft/Semi-supervised-learning#14]
## 🚀 Feature

Can you add download links for the NLP datasets that mentioned in the paper?

### Motivation

I tried to use huggingface datasets library to download the datasets, and found an inconsistent number of training data (e.g., for AGNews, your paper mentioned the training data number is 100,000, but huggingface reported a 120,000). Even consider the 10,000 validation data, there are still missing 10,000 training data.

### Pitch

I can have the exactly same training, validation, and test data for all NLP tasks, and reproduce your results.

**Comment by Hhhhhhao** [comment]
Hi, the dataset link will be added very soon. For the datasets with limited license, we will provide the corresponding processing code.
