### ISSUE TITLE
Results for Cifar100 and other datasets using classic settings

### ISSUE THREAD

**Issue by MemoriesJ** [microsoft/Semi-supervised-learning#142]
Hi,

thank you for your great efforts in sharing this public code base.
I noticed that you tested the codes using wrn28_2 on several benchmarks.
Do you have any plans to complete the experiments on those benchmarks using classic settings, for example using wrn28_8 on cifar100?

And I re-run the Freematch on cifar10 using the same settings (v100, same initial value, same hyperparameters) as you mentioned in the paper, but I got different results. Would you consider updating those results with consistent settings? 

For the Freematch, I got the following results using seed 0/1/2 for 
cifar10_40 | cifar10_250 | cifar10_4000
5.15±0.51 | 4.85±0.1 | 4.27±0.0

Thank you

**Comment by Hhhhhhao** [comment]
We do have provided results on classic benchmark, especially CIFAR-10, using USB codebase. 
Results are in this csv file: https://github.com/microsoft/Semi-supervised-learning/blob/main/results/classic_cv.csv
And corresponding logs are here: https://drive.google.com/drive/folders/1oEbcSqKcQfKvCFk3Z6XVXmPJLCt5ioSR
All the results and logs are obtained with semilearn 0.3.0. 

For CIFAR-100, running it on classic setting with wrn-28-8 would take too long (10 days on V100 at least), and we have no plans for running it currently.
