### ISSUE TITLE
[Question] Real impact of "args.gpu"

### ISSUE THREAD

**Issue by junha1125** [microsoft/Semi-supervised-learning#143]
Thank you for your nice and fantastic code.

In [train.py#L194](https://github.com/microsoft/Semi-supervised-learning/blob/main/train.py#L194), I can find: 
```python
if args.gpu is not None:
        warnings.warn('You have chosen a specific GPU. This will completely disable data parallelism.')
```

But when looking at [misc.py#L54](https://github.com/microsoft/Semi-supervised-learning/blob/main/semilearn/core/utils/misc.py#L54), I can see:
```python
if args.gpu is not None:
        model = nn.SyncBatchNorm.convert_sync_batchnorm(model)
        model = torch.nn.parallel.DistributedDataParallel(model, broadcast_buffers=False,
                                                                 find_unused_parameters=True,
                                                                 device_ids=[args.gpu])
```
This code means, if I set the specific `args.gpu`, I can use DDP (DistributedDataParallel), which helps us to **enable** data parallelism. 

I wonder why you warned `disable data parallelism` in train.py#L194. 
Q1. Did I understand your code correctly? 
Q2. Do you have a special reason that you left the warning?

**Comment by Hhhhhhao** [comment]
Hi, usually this parameter does not need to be set. If you are using DDP, you can just run with:
```
CUDA_VISIBLE_DEVICES=0,1 python train.py
```
and it goes with the default DDP.

Let me know if that helps.

**Comment by Betty-J** [comment]
According to the code, when you set args.gpu, you will only be able to use the specified GPU, so I think it will warn "This will completely disable data parallelism"

**Comment by Betty-J** [comment]
> Thank you for your nice and fantastic code.
> 
> In [train.py#L194](https://github.com/microsoft/Semi-supervised-learning/blob/main/train.py#L194), I can find:
> 
> ```python
> if args.gpu is not None:
>         warnings.warn('You have chosen a specific GPU. This will completely disable data parallelism.')
> ```
> 
> But when looking at [misc.py#L54](https://github.com/microsoft/Semi-supervised-learning/blob/main/semilearn/core/utils/misc.py#L54), I can see:
> 
> ```python
> if args.gpu is not None:
>         model = nn.SyncBatchNorm.convert_sync_batchnorm(model)
>         model = torch.nn.parallel.DistributedDataParallel(model, broadcast_buffers=False,
>                                                                  find_unused_parameters=True,
>                                                                  device_ids=[args.gpu])
> ```
> 
> This code means, if I set the specific `args.gpu`, I can use DDP (DistributedDataParallel), which helps us to **enable** data parallelism.
> 
> I wonder why you warned `disable data parallelism` in train.py#L194. Q1. Did I understand your code correctly? Q2. Do you have a special reason that you left the warning?

According to the code, when you set args.gpu, you will only be able to use the specified GPU, so I think it will warn "This will completely disable data parallelism"

**Comment by junha1125** [comment]
@Hhhhhhao Thank you so much. I understand.
@Betty-J Thank you for your reply. I want to mention what I learn so far.

Refer to: https://github.com/microsoft/Semi-supervised-learning/blob/main/train.py#L209
If you set multiple gpus, each process has its own `args.gpu` value, Ex, process1 has `args.gpu` as 1 and process2 has `args.gpu` as 2.
Refer to: https://github.com/microsoft/Semi-supervised-learning/blob/main/semilearn/core/utils/misc.py#L54
Each process defines its own model, respectively. i.e., if you set multiple gpus, you will have multiple model.
Refet to: https://github.com/microsoft/Semi-supervised-learning/blob/main/train.py#L239
All models defined in each process can communicate thank the above line.

Thus, when we use multiple gpus and set specific `args.gpu = 0`, the code start using DDPs. DDPs will **enable data parallelism**. Notably, the definition of `args.batch_size`is also changed, from `all batch size for all gpu` to `each batch size for each gpu` as mentioned in [misc.py#L49](https://github.com/microsoft/Semi-supervised-learning/blob/7065e703742a5ca4d85b2ac04d56fb7f7f2d380a/semilearn/core/utils/misc.py#L49). 

I hope you enjoy this fantastic repository like me. I learned a lot. 
Have a good day!
