### ISSUE TITLE
How to transform 3D data such as MedMNIST3D 

### ISSUE THREAD

**Issue by Betty-J** [microsoft/Semi-supervised-learning#145]
Hi, I noticed that the datasets available in the usb project include MedMINIST3D, but found such code in class MedMNIST3D(MedMNIST), I want to know how to perform transforms for 3D data, according to the code, I found that it will perform the same process as 2D data, because there is only one **get_medmnist**. Is this the correct way to do it ? And what does "return: (without transform/target_transofrm)" mean here
Looking forward to your reply
<img width="662" alt="截屏2023-08-17 11 04 34" src="https://github.com/microsoft/Semi-supervised-learning/assets/23076443/65abd98f-b9f6-4985-9e85-547b3f84756a">

**Comment by Hhhhhhao** [comment]
Hi, currently we have no support to 3D data and 3D backbone. 
You need to modify the augmentation and corresponding network architecture part.

**Comment by Betty-J** [comment]
> Hi, currently we have no support to 3D data and 3D backbone. You need to modify the augmentation and corresponding network architecture part.

Thanks for your reply, I still have a little doubt about the strong augment in ssl. I saw that the definition of the enhancement part in the code is to add the Normalize operation at the end of the transforms, but the strong augment seems to change the contrast, color and other information of the image. Will this cause the enhanced image to no longer conform to the original **pixel_mean** and **pixel_std**, will this have any impact on the model? please let me know if you have any insights on this issue, thanks again![截屏2023-08-25 11 12 15](https://github.com/microsoft/Semi-supervised-learning/assets/23076443/2d4d3a5a-5a46-44e5-b9d8-ebed79799036)
