### ISSUE TITLE
Why are only lb_data and lb_target used in 'Create dataset' section in "Customize datasets" tutorial

### ISSUE THREAD

**Issue by alysia2019** [microsoft/Semi-supervised-learning#147]
Hi,

I found that only lb_data and lb_target used for creating dataset [Custom_Dataset.ipynb](https://colab.research.google.com/drive/1zbswPm1sM8j0fndUQOeqX2HADdYq-wOw#scrollTo=Hkea92iFcOEq) is that a typo?

`
lb_data, lb_target, ulb_data, ulb_target = split_ssl_data(config, data, target, 10,
                                                          config.num_labels, include_lb_to_ulb=config.include_lb_to_ulb)
lb_dataset = BasicDataset(config.algorithm, lb_data, lb_target, config.num_classes, train_transform, is_ulb=False)
ulb_dataset = BasicDataset(config.algorithm, lb_data, lb_target, config.num_classes, train_transform, is_ulb=True, strong_transform=train_strong_transform)
eval_dataset = BasicDataset(config.algorithm, lb_data, lb_target, config.num_classes, eval_transform, is_ulb=False)
`

**Comment by Hhhhhhao** [comment]
Hi, this should be a typo. Thanks for point it out. 
You can open a PR to fix this or I will later.

**Comment by alysia2019** [comment]
> Hi, this should be a typo. Thanks for point it out.
> You can open a PR to fix this or I will later.

Thank you so much. :)
