### ISSUE TITLE
Possibility to eval on one single data

### ISSUE THREAD

**Issue by Edwinosse** [microsoft/Semi-supervised-learning#150]
Dear MicrosoftUSB Team,

Thank you a lot for your work. Is it possible to run eval.py function with a dataloader containing only one image data from Eurodataset? Outside evaluation during training, it is difficult to visually test out the results of an obtained model.

Thank you again

**Comment by Hhhhhhao** [comment]
Hi, you need to write the visualization code by yourself. If you can come up with something such as a general visualization function, you can open a PR and we'd love to have that function in the library.
