### ISSUE TITLE
Aim repository path is hard-coded

### ISSUE THREAD

**Issue by adamtupper** [microsoft/Semi-supervised-learning#151]
The path to the Aim repository inside the AimHook (see [here](https://github.com/microsoft/Semi-supervised-learning/blob/7065e703742a5ca4d85b2ac04d56fb7f7f2d380a/semilearn/core/hooks/aim.py#L24C50-L24C104)) is hard-coded. Therefore, the AimHook cannot be used unless this directory structure is replicated.

This could be fixed by adding a config value (and attribute to `AlgorithmBase`) named `aim_repo` and then modifying the `before_run` method of `AimHook`, i.e.,

```python
def before_run(self, algorithm):
    # initialize aim run
    name = algorithm.save_name
    project = algorithm.save_dir.split('/')[-1]
    repo = algorithm.aim_repo
    self.run = aim.Run(experiment=name, repo=repo)
    ...
```

I'm happy to open a PR to do this.

**Comment by Hhhhhhao** [comment]
> The path to the Aim repository inside the AimHook (see [here](https://github.com/microsoft/Semi-supervised-learning/blob/7065e703742a5ca4d85b2ac04d56fb7f7f2d380a/semilearn/core/hooks/aim.py#L24C50-L24C104)) is hard-coded. Therefore, the AimHook cannot be used unless this directory structure is replicated.
> 
> This could be fixed by adding a config value (and attribute to `AlgorithmBase`) named `aim_repo` and then modifying the `before_run` method of `AimHook`, i.e.,
> 
> ```python
> def before_run(self, algorithm):
>     # initialize aim run
>     name = algorithm.save_name
>     project = algorithm.save_dir.split('/')[-1]
>     repo = algorithm.aim_repo
>     self.run = aim.Run(experiment=name, repo=repo)
>     ...
> ```
> 
> I'm happy to open a PR to do this.

Hi, open a PR for this would be very helpful!
