### ISSUE TITLE
About warmup does not seem to take effect

### ISSUE THREAD

**Issue by Betty-J** [microsoft/Semi-supervised-learning#153]
Hi there, I am trying to use fixmatch for training. During training, I set num_warmup_iter in the config, but according to the records of events in tensorboards, warmup does not seem to take effect. I want to know if this behavior is normal. Thanks
<img width="422" alt="截屏2023-08-30 17 24 51" src="https://github.com/microsoft/Semi-supervised-learning/assets/23076443/d85d352b-1bfa-462c-ae39-944b89106f7b">

**Comment by Hhhhhhao** [comment]
I also think the warmup function might have some potential bugs (the learning rate scheduler part).
