### ISSUE TITLE
The problem with train_sampler

### ISSUE THREAD

**Issue by TTToby** [microsoft/Semi-supervised-learning#160]
Semi-supervised-learning-mian/semilearn/datasets/samplers/sampler.py  line 144
name2sampler = {
    'RandomSampler': DistributedSampler, 
    'WeightedRandomSampler': WeightedDistributedSampler}

Why does 'Randomsampler' correspond to 'DistributedSampler'? Looking forward to your reply. Thank you！

**Comment by Hhhhhhao** [comment]
We default to use distributed training.
