### ISSUE TITLE
Differences between the original paper and "results\classic_cv.csv".

### ISSUE THREAD

**Issue by cxyxxx** [microsoft/Semi-supervised-learning#165]
Dear MicrosoftUSB Team, We found that the results you showed in the "results\classic_cv.csv" file are quite different from the results shown in the original paper, especially for the cifar100 dataset.

Therefore, we would like to know what is the reason for this and what is the total training step in the experiment.
Thanks for your contribution.

**Comment by Hhhhhhao** [comment]
Hi, the csv file contains the most update-to-date results since we have made several significant updates after the publish of our paper. I think the general ranking of each algorithm doesn't get affect too much.
