### ISSUE TITLE
"Does your algorithm support semi-supervised segmentation tasks？

### ISSUE THREAD

**Issue by yusirhhh** [microsoft/Semi-supervised-learning#167]
"Does your algorithm support semi-supervised segmentation tasks, and if not, are there any plans for future development in this regard?"

**Comment by yusirhhh** [comment]
"Does your algorithm support semi-supervised segmentation tasks, and if not, are there any plans for future development in this regard?"

**Comment by Hhhhhhao** [comment]
> "Does your algorithm support semi-supervised segmentation tasks, and if not, are there any plans for future development in this regard?"

Hi, currently, we do not plan to extend to segmentation tasks. 
If you have any good ideas about the extension, please let us know!
