### ISSUE TITLE
Hard coding the dataset path

### ISSUE THREAD

**Issue by Bala93** [microsoft/Semi-supervised-learning#171]
## Bug

https://github.com/microsoft/Semi-supervised-learning/blob/main/semilearn/datasets/utils.py#L63
The dataset path is not being considered from args, instead it is hard-coded as 'data'

### Reproduce the Bug
fixmatch_ag_news_40_0.yaml, data_dir: ./nlp_data 

### Error Messages and Logs
Memory issue.

**Comment by Hhhhhhao** [comment]
Hi, would you like to open a PR for fixing this issue?

**Comment by Bala93** [comment]
Sure, will do
