### ISSUE TITLE
Unable to run eval.py on USB NLP Datasets

### ISSUE THREAD

**Issue by ShambhaviCodes** [microsoft/Semi-supervised-learning#172]
## Bug

Does the eval.py support NLP datasets?

**Comment by Bala93** [comment]
## Import this function
from semilearn.datasets import get_collactor 

## Use the collactor function in data_loader
collact_fn = get_collactor(args, args.net)
eval_loader = DataLoader(eval_dset, collact_fn)

## For handling dict data. 
if isinstance(x, dict):
    x = {k: v.cuda() for k, v in x.items()}
else:
    x = x.cuda()
