### ISSUE TITLE
possible to use semi-learn package on CPU-only device?

### ISSUE THREAD

**Issue by eliduval** [microsoft/Semi-supervised-learning#174]
Hi

I would like to use your Python package semi-learn but I am running into a GPU-related problem. Since my computer has no GPU, even very simple scripts (like the "Beginner example notebook") return a GPU/cuda- related error. I was wondering if there is a possible way  to work around this and so be able to use your package also on a CPU-only device?

Thanks in advance!

**Comment by mhmdghazal** [comment]
you need cuda
