### ISSUE TITLE
A Newbie Question: What does classic_cv and usb_cv mean, and what are their difference?

### ISSUE THREAD

**Issue by fclof** [microsoft/Semi-supervised-learning#175]

**Comment by Hhhhhhao** [comment]
class_cv means no pre-trained model is used
usb_cv means pre-trained model is used

**Comment by fclof** [comment]
Thanks for your explanation!

**Comment by ZahraaHM** [comment]
> class_cv means no pre-trained model is used usb_cv means pre-trained model is used

would you please explain more, as my understanding was like this(classic_cv use resnets and usb_cv use vit)
