### ISSUE TITLE
Time series analysis

### ISSUE THREAD

**Issue by poorvi0311** [microsoft/Semi-supervised-learning#181]
### Motivation

The semilearn library has made it pretty concise to implement various semi supervised algorithm to CV and NLP data but I wanted to know if it could be implemented for time series data too.

**Comment by jindongwang** [comment]
Of course it can be used in time series datasets. The algorithms are independent to applications. You are welcome to use it in time series applications:)

**Comment by poorvi0311** [comment]
How can the algorithms be modified for time series? I see a lot of functions are very specific to cv or nlp. Any reference for such applications?

**Comment by Hhhhhhao** [comment]
> How can the algorithms be modified for time series? I see a lot of functions in semilearn are very specific to cv or nlp. Any reference for such applications? Can semilearn as a package be used for time series analysis and not just algorithms?

I guess currently just algorithms. But It would be easy to adapt to time series since we already support sequential inputs.
