### ISSUE TITLE
Question about the Augmentation on Two-Moon dataset used in FreeMatch and SoftMatch

### ISSUE THREAD

**Issue by MemoriesJ** [microsoft/Semi-supervised-learning#183]
Hi,

I want to confirm which augmentation you used on the two-moon dataset as illustrated in FreeMatch and SoftMatch.
I checked your papers and codes here, but cannot find any details.
Appreciate it if you could specify.

**Comment by Hhhhhhao** [comment]
> Hi,
> 
> I want to confirm which augmentation you used on the two-moon dataset as illustrated in FreeMatch and SoftMatch. I checked your papers and codes here, but cannot find any details. Appreciate it if you could specify.

We add random Gaussian noise of different std
