### ISSUE TITLE
Customize datasets tutorial cant work

### ISSUE THREAD

**Issue by dddZhao** [microsoft/Semi-supervised-learning#186]
I got the same bug as #23 when running the function get_algorithm.
That bug has been fixed in Colab, but I still met this problem locally. In addition, I checked Algorithmbase, but I couldn't find a way to fix it.

**Comment by Hhhhhhao** [comment]
Can you check if the dataset name is in the datasets we support in the code? 
It won't affect the data loading but may cause some problems, as in #23. 
It would be easier to diagnose if you posted your error log here.

**Comment by dddZhao** [comment]
Thanks!
The dataset name is 'mnist' which I didn't download it. I changed it to 'cifar10' and it works now~
