### ISSUE TITLE
Train data with 4 channels 

### ISSUE THREAD

**Issue by kehuangke** [microsoft/Semi-supervised-learning#19]
## 🚀 Feature

Can the tool train 4 channels of data?

### Motivation

we construct our data into 3 channels and input it into TorchSSL model.  We want to use more information to improve the discriminant accuracy of the training model. However, after we construct our data into 4 channels, the model give me an error.

![image](https://user-images.githubusercontent.com/45514301/191681686-81bd9b9b-0444-43f1-99eb-ae273ed6fa88.png)

### Additional context

<!-- Add any other context or screenshots about the feature request here. --

**Comment by Hhhhhhao** [comment]
Hi, currently we only support CNNs on natural images with 3 channels:
https://github.com/microsoft/Semi-supervised-learning/blob/0b73e350fff3d8b564453c627f67d1a7c4644dc9/semilearn/nets/wrn/wrn.py#L84

You can try to create you own network or replace the current one with 4 channels input.
