### ISSUE TITLE
The pretrained model of STL-10

### ISSUE THREAD

**Issue by kleinzcy** [microsoft/Semi-supervised-learning#20]
In table13, the reported pretrained model of STL-10 is ViT-B-P16-96. But in your code, the pretrained backbone is mae_pretrain_vit_base. I am curious which one is used in your paper?

**Comment by Hhhhhhao** [comment]
The backbone is ViT-B-P16-96 and the pretrained checkpoint used is "mae_pretrain_vit_base".

This is not conflict because the difference between them is only the position embedding which will be resized from 196 (224 images) to 36 (96 images), with the same patch size of 16.

**Comment by kleinzcy** [comment]
Thanks to your quickly response.
