### ISSUE TITLE
som question about get_cosine_schedule_with_warmup

### ISSUE THREAD

**Issue by wenyuhaokikika** [microsoft/Semi-supervised-learning#206]
Hello , thanks for Semi-supervised-learning,

[semilearn/core/utils/build.py:217:def get_cosine_schedule_with_warmup](https://github.com/microsoft/Semi-supervised-learning/blob/08334816951fef8e770e435b04a88de3c1427f2b/semilearn/core/utils/build.py#L217)

I want to know why  num_cycles set 7. / 16，have some referance？

And I checked the original algorithm of the [cosine Annealing algorithm](https://arxiv.org/abs/1704.00109). It seems to be slightly different from the version in the code. Is it possible that TorchSSL does not use the original algorithm but a self-set algorithm with a reduced learning rate? or I found a wrong reference paper?

![reference](https://github.com/microsoft/Semi-supervised-learning/assets/40107519/40a17be1-575f-494c-b849-294aaee2f639)

and TorchSSL is :

![image](https://github.com/microsoft/Semi-supervised-learning/assets/40107519/bc0cf304-67e3-4524-a888-aaa8ba3ac7c3)

Looking forward for your reply, thank you~~~

```[tasklist]
### Tasks
```

**Comment by wenyuhaokikika** [comment]
why close?

**Comment by Hhhhhhao** [comment]
> why close?

Seems to be a stale close. 
The num_cycle of 7/16 is set as a default since FixMatch paper. You can find more details there.
