### ISSUE TITLE
There is CIFAR-400 in the papaer

### ISSUE THREAD

**Issue by hnuliuxin** [microsoft/Semi-supervised-learning#213]
The description of Figure2 has mentioned cifar400, which may be a mistake.
![image](https://github.com/microsoft/Semi-supervised-learning/assets/66301198/eef35b0e-dc09-4982-b058-4baea2929733)

**Comment by Hhhhhhao** [comment]
Thanks for point it out. It is indeed a mistake, which should be CIFAR-100 with 400 labels. 
We will try to fix this in the future.
