### ISSUE TITLE
Assertion on pseudolabel 

### ISSUE THREAD

**Issue by mioam** [microsoft/Semi-supervised-learning#215]
When I use "pseudolabel" which does not require a strong_transform, the assertion appears:

```
AssertionError: alg pseudolabel requires strong augmentation
```

I wonder if there is something wrong in https://github.com/microsoft/Semi-supervised-learning/blob/6cf697e6968f9f77040a9e0162306436a91a00dc/semilearn/datasets/cv_datasets/datasetbase.py#L59, which should be
```
assert self.alg in ['fullysupervised', 'supervised', 'pseudolabel', 'vat', 'pimodel', 'meanteacher', 'mixmatch',], f"alg {self.alg} requires strong augmentation"
``` 

Maybe "refixmatch" also requires a strong augmentation.

**Comment by Hhhhhhao** [comment]
Thanks for pointing that out. Would you like to open a PR for making this change?
