### ISSUE TITLE
Is this a bug of algorithm mean teacher?

### ISSUE THREAD

**Issue by hellojinjie** [microsoft/Semi-supervised-learning#226]
https://github.com/microsoft/Semi-supervised-learning/blob/6cf697e6968f9f77040a9e0162306436a91a00dc/semilearn/algorithms/meanteacher/meanteacher.py#L54-L56
we get outs_x_ulb_s in line 54, but we use outs_x_ulb_w in line 55 and 56?
![QQ_1721629356730](https://github.com/user-attachments/assets/ac86ccc3-84e1-48dc-b5f0-4ba742fe1cba)

**Comment by Hhhhhhao** [comment]
This seems to be a bug. Would you mind to open a PR for this?
