### ISSUE TITLE
About ImageNet127 dataset

### ISSUE THREAD

**Issue by Sheldon04** [microsoft/Semi-supervised-learning#227]
Hello! I've noticed that you have provided config files in config/classic_cv_imb about imagenet127 dataset. However, there's no descriptions about how to get the dataset. Is this dataset the same as CoSSL (Small ImageNet 127 with size 32/64). And the ing_size in your files is set to 112. I wonder if there are more details. Thanks!

**Comment by Hhhhhhao** [comment]
Yes. The IN-1K 127 dataset is often used in long-tailed setting, and we use that directly (with original resolution).
