### ISSUE TITLE
configure the iteration count

### ISSUE THREAD

**Issue by liyan0808** [microsoft/Semi-supervised-learning#230]
In the configuration of a class imbalance algorithm using the CIFAR-10 dataset, with an imbalance ratio of 100 between labeled and unlabeled data, where the head class has 500 labeled instances and 4000 unlabeled instances, why are the training iterations set to 262,144, the epochs to 256, and the batch size to 64? I look forward to your prompt reply.

**Comment by Hhhhhhao** [comment]
This is mainly followed the previous training protocols in class balanced settings.

**Comment by liyan0808** [comment]
> 这主要遵循之前在课堂平衡设置中的训练方案。

Thank you for your prompt reply.
