### ISSUE TITLE
Default value for ulb_num_labels

### ISSUE THREAD

**Issue by kleinzcy** [microsoft/Semi-supervised-learning#27]
When I run the updated code, I find a bug if ulb_num_labels is None.

The error is "ssl/semilearn/datasets/utils.py", line 101, in sample_labeled_unlabeled_data: UnboundLocalError: local variable 'ulb_samples_per_class' referenced before assignment".

A default value has to be set for ulb_num_labels.

**Comment by Hhhhhhao** [comment]
We also found this bug, for now you and add another condition in if "ulb_num_labels != 'None'". We will fix this issue in the next update.
