### ISSUE TITLE
Does USB offer semi- or weakly- supervised Object detection?

### ISSUE THREAD

**Issue by amirhesamyazdi** [microsoft/Semi-supervised-learning#31]
## 🚀 Feature

The existing WSOD (Weakly Supervised Object Detection) algorithms are very much tailored towards COCO dataset and are very unreliable for custom datasets. And models like omni-detr are very resource demanding requiring very expensive GPUs (32GB GPUs and up) to train properly. 

I was wondering if USB offers or will offer Object Detection. In similar ways that DETR and Faster RCNN offer, but weakly supervised.

### Additional context

<!-- Add any other context or screenshots about the feature request here. --

**Comment by qianlanwyd** [comment]
Currently we are focusing on classification tasks. However, any pull reqeust is welcome, if you have any ideas or want to contribute, feel free to contact.
