### ISSUE TITLE
extra algorithoms used in Benchmark Results

### ISSUE THREAD

**Issue by qintuswind** [microsoft/Semi-supervised-learning#33]
Hi, I wonder the details of the extra algorithoms mentioned in Benchmark Results, .e.g, freematch/softmatch/mpl, would u like to offer the  detailed information or articles about them?

**Comment by Hhhhhhao** [comment]
We are still working on the reproduction of these algorithms. Once we have the correct implementation and results we will make these algorithms released.

**Comment by qintuswind** [comment]
ok, thanks U

**Comment by Hhhhhhao** [comment]
It hs not published yet, but you can find it here: https://openreview.net/forum?id=ymt1zQXBDiF

**Comment by Adamdad** [comment]
> Hi, I wonder the details of the extra algorithoms mentioned in Benchmark Results, .e.g, freematch/softmatch/mpl, would u like to offer the detailed information or articles about them?

Looking forward to those implementations.
