### ISSUE TITLE
Exception: Size of sample #521 is invalid (=(1029, 0)) since max_positions=(1024, 1024), skip this example with --skip-invalid-size-inputs-valid-test

### ISSUE THREAD

**Issue by ZhengxiangShi** [microsoft/Semi-supervised-learning#34]
Hi,

Thanks for this nice project.

I encounter an error when running `python preprocess/preprocess_aclimdb.py`. The error `Exception: Size of sample #521 is invalid (=(1029, 0)) since max_positions=(1024, 1024), skip this example with --skip-invalid-size-inputs-valid-test` happens at the `cur_aug_sen_0 = de2en.translate(en2de.translate(cur_ori_sen,  sampling = True, temperature = 0.9),  sampling = True, temperature = 0.9)`. I am not familiar with fairseq. How could I fix this?

Thanks a lot.

**Comment by Hhhhhhao** [comment]
Hi, the translation model used requires the maximum length of sentence to be 1024, so we cut the sentence during preprocess.
