### ISSUE TITLE
Dataset Files Missing

### ISSUE THREAD

**Issue by ZhengxiangShi** [microsoft/Semi-supervised-learning#37]
Hi,

The train.json in yahoo_answers and test.json in amazon_review are missed in your dataset zip file.

Could you please update it? 

Thanks

**Comment by Hhhhhhao** [comment]
Good catch! We will update the download link with full data. 

For your convenience, I have also uploaded the missing json files here: https://drive.google.com/drive/folders/1Ii3J3dPOwhbsmQHJaghVY2lZsvrg17W2?usp=sharing

**Comment by ZhengxiangShi** [comment]
Many thanks
