### ISSUE TITLE
How to use tensorboard with custom datasets

### ISSUE THREAD

**Issue by Natsuki03** [microsoft/Semi-supervised-learning#40]
Hi.
I want to create a graph using tensorboard with a custom dataset.
However, the [tutorial](https://colab.research.google.com/drive/1zbswPm1sM8j0fndUQOeqX2HADdYq-wOw) did not show how to create it.
Can you tell me how to do this?
Thanks.

**Comment by Hhhhhhao** [comment]
Add your graph data to tb_dict as output of the algorithm and change it here: https://github.com/microsoft/Semi-supervised-learning/blob/067b0f062333f14bf0ca15beb83d785dab7db74d/semilearn/core/hooks/logging.py#L19

**Comment by Natsuki03** [comment]
I was able to create it!
Thanks very match.
