### ISSUE TITLE
Arguments Display bug

### ISSUE THREAD

**Issue by MemoriesJ** [microsoft/Semi-supervised-learning#41]
Hi,

Thanks for providing this wonderful code base.
I understand that there should be a huge amount of work so any mistakes are possible.
While I was trying to run with distributed parallel training, I found that the argument display for batch size might be wrong.

i.e., train.py line 255 -> send_model_cuda -> misc.py line 52
this line will further change the batch size by half while declaring and defining the EMA model.

I politely want to double-check this with you and appreciate you if you could clarify this.
 
By the way, May I ask will the FreeMatch be also included in the next commit?

Cheers and Thanks

**Comment by MemoriesJ** [comment]
Hi Hao,

May I ask will the FreeMatch will be also included in the next commit?

**Comment by qianlanwyd** [comment]
Could you show us the commands and logs so we can further help you debug?

We will open source FreeMatch in a few months.

**Comment by MemoriesJ** [comment]
Yeah, I know the shape is correct, and printed batch size won't have a harmful effect.
The initializing of the sampler and data loader has been done before this logging process.
But it actually should be 32 instead of 16 in my example above.

**Comment by MemoriesJ** [comment]
Hi,

I am not saying the format is wrong, the number of GPUs is incorrect, or the model performance will be affected.

The only problem is the displayed number for batch size in the log file.
For the current codes, the batch size in the log file will be 16, and the number of GPUs will be 2.
However, it is expected to be 32 and 2, respectively. since the specified one is 64 under the world size 2 set.

Please let me know if I misunderstand it.

**Comment by qianlanwyd** [comment]
Hi, to use multiple gpus, I recommend  the following commands:
CUDA_VISIBLE_DEVICES=0,1  python train.py --c xx.yml
If there is still bug, please let me know.

**Comment by MemoriesJ** [comment]
Hi,

I saw your updates. My solution is similar to yours.
Thanks for the update.

**Comment by MemoriesJ** [comment]
Hi Yidong,

Sorry for bothering you again.

I am trying to understand the FreeMatch,
May I ask you for some details about the FreeMatch?
1. The initial value h_tilde has not been mentioned in the paper. Is it the same as the initial value of p_tilde, i.e., 1/C?
2. how do you process the zero division problem of equation 11?  since the h_bar will have some zero values, and the h_tilde as well if it is not initialized with 1/C.
3. and will there be any gradients from h_tilde and h_bar?

Thank you in advance

**Comment by jindongwang** [comment]
Hi @MemoriesJ,

Thanks for your interest in FreeMatch. I think it is better that you ask the details about FreeMatch outside of this repo since FreeMatch is currently not implemented in this repo:) You can email him instead.

**Comment by MemoriesJ** [comment]
Sure. thank you.

**Comment by qianlanwyd** [comment]
please also cc Hao Chen.

**Comment by MemoriesJ** [comment]
> please also cc Hao Chen.

definitely will do that. thanks.
