### ISSUE TITLE
Batch size mismatch in the paper and the code

### ISSUE THREAD

**Issue by harrylin-hyl** [microsoft/Semi-supervised-learning#42]
![image](https://user-images.githubusercontent.com/26209785/204529292-5aa5d552-87bf-49be-b3b8-26abca0edc86.png)
![image](https://user-images.githubusercontent.com/26209785/204529446-6243a08a-6316-4f93-a7ff-12b11d24470b.png)

Wonderful work! 
But I found  a batch size mismatch problem between paper and code. The batch size is reported as 16 and 16 for labeled and unlabeled data, but the batch size is implemented as 8 and 8 for labeled and unlabeled data in code.

**Comment by Hhhhhhao** [comment]
Please follow the script and config files. The batch size in paper might not be changed since we have several updates after the paper and we will fix it.

**Comment by harrylin-hyl** [comment]
Got it! Thanks.
