### ISSUE TITLE
An error in training the EuroSat dataset

### ISSUE THREAD

**Issue by harrylin-hyl** [microsoft/Semi-supervised-learning#45]
![image](https://user-images.githubusercontent.com/26209785/206659536-58064c4c-96b4-461b-aba4-4baef061c3ef.png)
![image](https://user-images.githubusercontent.com/26209785/206659572-b1e22f6f-870b-421e-bde7-fb94e49ab47b.png)

FileNotFoundError: Found no valid file for the classes labeled_idx. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

**Comment by Hhhhhhao** [comment]
Can you check your data folder path for EuroSat? Looks like a path error instead of package error.

**Comment by harrylin-hyl** [comment]
![image](https://user-images.githubusercontent.com/26209785/206836736-e55c6fb6-b290-4cd8-a411-d211a1471bdf.png)
I have followed the data folder setting as the project list.

**Comment by Hhhhhhao** [comment]
can you also crop the config file you are running?

**Comment by harrylin-hyl** [comment]
**I have found this error!**
 As shown in the figure, A labeled_idx folder will be created by your code to identify different image ids with different seeds. But the ImageFolder class will treat the folders in this path as certain categories including the labeled_idx folder. Therefore, this error is produced. 
![206836736-e55c6fb6-b290-4cd8-a411-d211a1471bdf](https://user-images.githubusercontent.com/26209785/206886682-375f9517-27b2-4353-84c4-ea8e64e1205e.png)

**Solution:**
We need to change the data path as the bottom figure shown:
![image](https://user-images.githubusercontent.com/26209785/206886913-164a2486-65c0-4671-ac05-38e039ec66b7.png)
Then, we change the code in the "eurosat.py" file as:
![image](https://user-images.githubusercontent.com/26209785/206886950-ad6b4ac8-e6a9-4877-9e95-9dacbece604c.png)
After that, the program works fine.

**Comment by pizhn** [comment]
Seems like it's an issue with your datafolder structure design. And I still need to modify the source code to make it runnable. Are you planning to address this?
