### ISSUE TITLE
Colab examples being crashed

### ISSUE THREAD

**Issue by erhanbicerr** [microsoft/Semi-supervised-learning#46]
Hi!

**Beginning and customizing dataset** examples in **colab** are crashing. I have tried it with **several google accounts.** Colab just returns **session has been crashed** when trying to import **semilearn** stuff.

Also; I've been trying a lot to work with the USB. Yet, even I have used Docker, I am unable to execute training process. Returns CUDA:Unknown Error. May be I should open another issue for that. **Still, I wonder if anyone can run and use this library seamlessly recently.**

**Comment by Hhhhhhao** [comment]
Thanks for reporting this. Since recently there are a few update of USB, we will soon update the semilearn package and codebase.

**Comment by Hhhhhhao** [comment]
Fixed in 69a2afc8ecc9ec29cbf6afb123035d2be3443568
