### ISSUE TITLE
Which pretrain is used in the CV task?

### ISSUE THREAD

**Issue by kleinzcy** [microsoft/Semi-supervised-learning#49]
Thanks to your great work to accelerate the research in SSL. After reading the paper, I have not figure out which pretrained model is used in the CV task. Unsupervised pretrain or supervised pretrain on imagenet?

**Comment by Hhhhhhao** [comment]
For STL-10, we use unsupervised pretraining on ImageNet (MAE).
And for other datasets we use supervised pretrianing.

**Comment by kleinzcy** [comment]
Why not to use unsupervised pretraining for all dataset?

**Comment by Hhhhhhao** [comment]
At the beginning we didn't get good results from unsupervised pretraining. But now we do plan to update the unsupervised pretraining results.

**Comment by kleinzcy** [comment]
I understand your concern on the model size. In my opinion, the motivation of SSL is to learn from limited label. But the supervised pretraining needs a lot of label data which is conflict to the motivation of SSL. What's more, the categories of downstream task may overlap with the pretrained categories. Therefore, I believe the plan to update the unsupervised pretraining results is more useful to the SSL community.
