### ISSUE TITLE
Regression Extension

### ISSUE THREAD

**Issue by pintonos** [microsoft/Semi-supervised-learning#5]
Hi,
thank you for the work on this project!

I am interested in applying this code for regression or even multi-target regression tasks. You stated in your paper that regression is currently not supported. I was wondering if you see any specific hurdles by extending the code to reach this goal? Does it even make sense to use these algorithms for non-classification tasks?

Thx in advance!

Best,
Andreas

**Comment by Hhhhhhao** [comment]
Hi,

To my knowledge, current semi-supervised regression algorithms differ from classification algorithms a lot, and current supported algorithms cannot be adapted to classification tasks easily. 
But we are working on extending USB to various tasks, including regression, imbalanced semi-sup, and open-set semi-sup, and we will be updating very soon!
