### ISSUE TITLE
Typo in Results of Classic CV?

### ISSUE THREAD

**Issue by nhaH-luaP** [microsoft/Semi-supervised-learning#53]
Looking at the results table for classic_cv, i noticed that for cifar10 there was a cifar10_4000 column. 

![image](https://user-images.githubusercontent.com/93386708/213188971-70d41c9e-f022-4c0d-897c-efb34efb55c5.png)

But with regards to the explanations you gave in the README.md of [Semi-supervised-learning/results/](https://github.com/microsoft/Semi-supervised-learning/tree/main/results), it should be 4, 25 and 100 labels per class and therefore cifar10_40, cifar10_250 and cifar10_1000 or am i missing something?

Greetings,
Paul

**Comment by Hhhhhhao** [comment]
The setting CIFAR-10 is slightly different from other settings. It is meant to have 4, 25, and 400 labels, while others have 4, 25, and 100 labels.

**Comment by nhaH-luaP** [comment]
Alright, thanks for the quick answer! Than this should probably be changed 

![image](https://user-images.githubusercontent.com/93386708/213392410-13aaf7e5-f95b-49c9-853c-7c0cad296d62.png)

**Comment by Hhhhhhao** [comment]
Fixed in 69a2afc8ecc9ec29cbf6afb123035d2be3443568
