### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by jo6815en** [microsoft/Semi-supervised-learning#54]
Hi!

I follow the instructions in the README, after training FixMatch the evaluation fails. Running the evaluation as described in the README generated a long list och missing keys and unexpected keys. 

Traceback (most recent call last):
  File "eval.py", line 54, in <module>
    keys = net.load_state_dict(load_state_dict)
  File "/home2/johannae/anaconda3/envs/usb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for WideResNet:
	Missing key(s) in state_dict: "conv1.weight", "conv1.bias", [...] "fc.bias". 
	Unexpected key(s) in state_dict: "cls_token", "pos_embed", "patch_embed.proj.weight", [...] , "head.bias".

**Comment by Hhhhhhao** [comment]
Hi,

From the error, looks like you init the net with WideResNet but your checkpoint state dict is from ViT. 
If you change the net argument in eval.py, this error should be resolved.

**Comment by jo6815en** [comment]
Thank you!
