### ISSUE TITLE
Multi GPU really accelerates the training?

### ISSUE THREAD

**Issue by twmht** [microsoft/Semi-supervised-learning#55]
From the code for multi gpu training, you expand the number of samples by the number of gpus (https://github.com/microsoft/Semi-supervised-learning/blob/main/semilearn/core/utils/build.py#L158), but you never decrease the number of iterations, so multi gpu can not really accelearate the training.

From the other repo, they do divide the number of batch size by the number of gpus (https://github.com/LeeDoYup/FixMatch-pytorch/blob/main/train.py#L155), do you have any idea?

**Comment by Hhhhhhao** [comment]
We intend to fix the total number of iterations as a protocol for semi-supervised learning.

**Comment by limberc** [comment]
Have you finished the multi-gpu setup? @Hhhhhhao

**Comment by sachinmotwani20** [comment]
> Have you finished the multi-gpu setup? @Hhhhhhao

I have the same concern. It doesn't seems.
