### ISSUE TITLE
Question about seed and the number of GPUs when you train

### ISSUE THREAD

**Issue by misoyuri** [microsoft/Semi-supervised-learning#63]
Hi,
Thanks for your great efforts.

Currently, I reproduce the results that you shared in this repo.
But, when I followed the recipes that you announced, the loss and accuracy is not exactly followed with your released logs.

Even if utilized with the same seed, the loss could be different.

and, in my case, I currently use a single GPU(RTX3090).
I just want to know how many GPUs are used when you trained the models.

Thank you.

**Comment by qianlanwyd** [comment]
We use single V100 for training.
From my personal experience, it is impossible for us to reproduce exactly the same results. Hardware and software differences can have an impact on the results. It is okay if the results are slightly different.
