### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Chiya8** [microsoft/Semi-supervised-learning#64]
![Error](https://user-images.githubusercontent.com/124553603/216897941-2947dfa3-dd09-4afb-9933-317a15d72c6d.jpg)

Hi,

When I am trying to run the code getting the following Error. 

**AttributeError: 'Namespace' object has no attribute 'use_amp'.**

Please help in fixing out the error.

Thank you.

**Comment by MemoriesJ** [comment]
Hi,

You may need to update the codes or git pull again.
This has already been fixed in PR#62
