### ISSUE TITLE
loading fain in Checkpoint

### ISSUE THREAD

**Issue by Chiya8** [microsoft/Semi-supervised-learning#66]
Hi,

![Error in Eval](https://user-images.githubusercontent.com/124553603/217172075-df2b52f0-3662-4887-8d6d-89c8ebb4a03b.jpg)
 In evaluation step I am unable to clear the error related to Checkpoint. Please do needful.

**Comment by qianlanwyd** [comment]
/path/to/checkpoint is an example，change it to your real checkpoint path.

**Comment by Chiya8** [comment]
After training, where the check points are saved

**Comment by qianlanwyd** [comment]
It depends on the save_dir in the used yaml

**Comment by Hhhhhhao** [comment]
closed with no further response
