### ISSUE TITLE
AttributeError: 'DistributedSampler' object has no attribute 'num_samples'

### ISSUE THREAD

**Issue by MRK4863** [microsoft/Semi-supervised-learning#7]
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-18-57c2708759ac>](https://localhost:8080/#) in <module>
      1 # define data loaders
----> 2 train_lb_loader = get_data_loader(config, lb_dataset, config.batch_size)
      3 train_ulb_loader = get_data_loader(config, ulb_dataset, int(config.batch_size * config.uratio))
      4 eval_loader = get_data_loader(config, eval_dataset, config.eval_batch_size)

1 frames

[/content/drive/MyDrive/RUPESH_RESEARCH_IMPLEMENTATIONS/Semi-supervised-learning/semilearn/datasets/utils.py](https://localhost:8080/#) in get_data_loader(args, dset, batch_size, shuffle, num_workers, pin_memory, data_sampler, num_epochs, num_iters, generator, drop_last, distributed)
    161         num_samples = per_epoch_steps * batch_size * num_replicas
    162         # print(num_samples)
--> 163         return DataLoader(dset, batch_size=batch_size, shuffle=False, num_workers=num_workers, collate_fn=collact_fn,pin_memory=pin_memory, sampler=data_sampler(dset, num_replicas=num_replicas, rank=rank, num_samples=num_samples),
    164         generator=generator, drop_last=drop_last)
    165 

[/content/drive/MyDrive/RUPESH_RESEARCH_IMPLEMENTATIONS/Semi-supervised-learning/semilearn/datasets/samplers/sampler.py](https://localhost:8080/#) in __init__(self, dataset, num_replicas, rank, num_samples)
     29     def __init__(self, dataset, num_replicas=None, rank=None, num_samples=None):
     30         if not isinstance(num_samples, int) or num_samples <= 0:
---> 31             raise ValueError("num_samples should be a positive integeral value, but got num_samples={}".format(self.num_samples))
     32 
     33         if num_replicas is None:

AttributeError: 'DistributedSampler' object has no attribute 'num_samples'
---------------------------------------------------------------------------------------------

Any suggestions on how to solve this issue?

**Comment by Hhhhhhao** [comment]
I think the "AttributeError" you got is a bug regarding the ValueError, but the reason is because the num_samples passed to sampler is not a int or less equal to 0, can you check the value of this varaible?

**Comment by MRK4863** [comment]
Yeah Hao,
Figured it out the hard way.
and the source of the AttributeError is "format(self.num_samples))"

"self.num_samples" is called before initializing "self.num_samples"
I rechanged it to just "num_samples".

After that, it showed me that my num_samples value is Zero.

The issue is resolved now, Thanks a ton!!
