### ISSUE TITLE
Wrong configurations

### ISSUE THREAD

**Issue by beandkay** [microsoft/Semi-supervised-learning#75]
## Bug
I saw that you have mistakenly change the model use for training **cifar-100** from **wrn-28-8** to **wrn-28-2**.
Moreover, seems like the argument **amp** is not used, instead, in your code, it is **use_amp**.

**Comment by Hhhhhhao** [comment]
We specifically change cifar100 model from wrn-28-8 to wrn-28-2 since wrn-28-2 takes too long to train. 

use_amp is not used and has been fixed in 64943855766de7bea6a0c333d688cb86ae1634f0
