### ISSUE TITLE
[Question/Suggestion] How to determine the number of training and evaluation iterations?

### ISSUE THREAD

**Issue by erhanbicerr** [microsoft/Semi-supervised-learning#77]
Hello,
Is there any rule to determine the number of training and evaluation iterations? I see from the source code of "Trainer" that 1 epoch continues until "train_iter" number of iterations are finished. Since the labelled and unlabelled data loaders do not contain same amount of data, how to determine the number of iteration? I would be appreciated if you could explain these parameters.

As a suggestion, it would be great if you could prepare and publish a docstring regarding parameters in config to clarify the goal of such parameters. 

Thank you for making such library open to use! Best.

**Comment by erhanbicerr** [comment]
Also, I assume that epochs are not the standard epochs that we know, increasing epochs could lead to exception in data loader:
`num_samples should be a positive integeral value, but got num_samples=0`
Do epochs should be decided according to the number of the samples?

**Comment by Hhhhhhao** [comment]
You are right. The epochs here is quite different from standard epochs we know. 

We follows Google setting. You should set total number of iterations first (10240000 in our case), and then number of training iterations per epoch. Then you calculate the epochs based on these two numbers specified.
