### ISSUE TITLE
[Question/Features] How can I use the self dataset and model in semilearn?

### ISSUE THREAD

**Issue by sundial-dreams** [microsoft/Semi-supervised-learning#78]
I have a dataset and model that I built, and how do I use that semilearn to do SSL?
My dataset can be summarized as:

|  dataset   |      num_classes     | labeled_per_samples | unlabeled_per_samples | test_per_samples | shape|
|------|----------|----------|----------|----------|----------|
| AIS-dataset | 50 | 10 | 120 | 130 | 1 $\times$ 256 |

And my model is use one-dimension signal as input (AIS-dataset).

**Comment by Hhhhhhao** [comment]
Hi there,

We have a custom dataset example in the notebook.

For custom model, currently the codebase are not that flexible. You need to add your model into nets accordingly.
