### ISSUE TITLE
Mismatch in performance in train log and eval code

### ISSUE THREAD

**Issue by Bala93** [microsoft/Semi-supervised-learning#8]
I am not able to obtain the same accruacy as shown in train log using eval code. Do you have any suggestions ?

**Comment by Hhhhhhao** [comment]
Can you provide more details? On which dataset and which algorithm you cannot reproduce the results?

**Comment by Hhhhhhao** [comment]
Thanks for pointing this out. In classic CV setting, we always use the ema model to do evaluation rather than the model itself.   We will update the evaluation code soon in this repo. 

Regarding the large difference you can check: https://arxiv.org/abs/1806.05594

**Comment by Bala93** [comment]
https://github.com/microsoft/Semi-supervised-learning/blob/main/eval.py#L39-L44. I also did the same while using it for evaluation. But, does "module" key gets added even when we use only one GPU for training ? In that case, this would break the code. I think it would be better to handle it in test code, like you have done in train code.

**Comment by Hhhhhhao** [comment]
Thanks for the suggestions. The evaluation script is rather simple for now and not robustly tested. We will update it very soon and also the pip module.

**Comment by Bala93** [comment]
Thank you for your prompt response. I would be happy to contribute, if you have any suggestions, let me know.
