### ISSUE TITLE
Add code of Simis

### ISSUE THREAD

**Issue by Parskatt** [microsoft/Semi-supervised-learning#83]
## 🚀 Feature

Code implementation of SimiS (https://arxiv.org/abs/2211.11086).

### Motivation
The paper reports high performance and would be a good addition to the repo.
The authors @Hhhhhhao seem to have already added configs (see: https://github.com/microsoft/Semi-supervised-learning/tree/main/config/classic_cv_imb/fixmatch_simis), but not the actual implementation.

**Comment by Hhhhhhao** [comment]
Still a pending work. Will release when it is ready. https://github.com/microsoft/Semi-supervised-learning/issues/68
