### ISSUE TITLE
Use softmatch for semi-supervised image segmentation

### ISSUE THREAD

**Issue by Fyw1988** [microsoft/Semi-supervised-learning#90]
Hello, I tried to use your softmatch for semi-supervised image segmentation, treating each pixel as a dichotomy, but found that the mask calculated for each pixel is a fixed value except 1 (0.9999998807907104). There will not be significantly more masks less than 1 as the training cifar dataset does with iteration. Is there any adjustment if you want to use softmatch for semi-supervised segmentation?

**Comment by Hhhhhhao** [comment]
I'm not quite familiar with semi-supervised image segmentation. Can you specify more details? Or you can add my wechat account so we can discuss more on that.

**Comment by Fyw1988** [comment]
> I'm not quite familiar with semi-supervised image segmentation. Can you specify more details? Or you can add my wechat account so we can discuss more on that.

Thank you very much for your work! I've seen what went wrong
