### ISSUE TITLE
Access labels for unlabeled set during training

### ISSUE THREAD

**Issue by Li-Muyang** [microsoft/Semi-supervised-learning#92]
Hi, for some reasons, I'd like to access the labels for unlabeled set during training, for instance, when I want to assess the quality of psudeo labels. How can I achieve this?

**Comment by qianlanwyd** [comment]
For cv datasets, modify this function: https://github.com/microsoft/Semi-supervised-learning/blob/main/semilearn/datasets/cv_datasets/datasetbase.py#L72

**Comment by Li-Muyang** [comment]
Hi Yidong, thanks for the reply. However during this time I come up with an alternative solution, which I think is probably easier. First, pass `idx_ulb` to `train_step`, then, simply use `self.dataset_dict['train_ulb'].__sample__(idx_ulb)` will return the labels of unlabeled training and raw inputs during training process. 

Please do point out if there is any flaw in doing so.

**Comment by Hhhhhhao** [comment]
Probably the most easy way to do this is:
1. Add y_ulb as one of the output of dataset getitem.
2. Add y_ulb in your train_step function argument. (As long as it appears in arguments the base class will handle it and send it to cuda.)

Hope this helps.

**Comment by Li-Muyang** [comment]
Noted, thanks!
