### ISSUE TITLE
Softmax function appears to be applied twice in the implementation of the Softmatch method. 

### ISSUE THREAD

**Issue by GeondoPark** [microsoft/Semi-supervised-learning#95]
At the code line 54 in "semilearn/algorithms/softmatch/utils.py", variable of **softmax_x_ulb** set as true. 
But at the code line 83 in "semilearn/algorithms/softmatch/softmatch.py", the **prob_x_ulb_x** is also output of the softmax function and feed to masking function in SoftMatchWeightingHook.

In my understanding, softmax function appears to be applied twice in the implementation of the Softmatch method. 
Could you check the implementation again? :)

Thanks.

**Comment by Hhhhhhao** [comment]
We also noticed this implementation error. You should set the second usage of the probability as without using softmax. We will update the results soon. Torchssl has the correct implementation and you can reference that for now.
