### ISSUE TITLE
win10 fail to install aim

### ISSUE THREAD

**Issue by jafer11** [microsoft/Semi-supervised-learning#99]
How to install aim in Windows10, I am using pip install aim command error. The error message is as follows:

Collecting aim
  Using cached aim-3.17.3.tar.gz (1.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.4.0 (from versions: 0.2.0)
      [end of output]
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Hhhhhhao** [comment]
A short solution would be comment out the aim installation in requirements.txt.

**Comment by jafer11** [comment]
The same problem will arise again

**Comment by jafer11** [comment]
The error message is as follows：
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/75/5d/0de5877f6aa71678ccaa230058f802a9405f7f60d07a990e4a28a5771d97/aim-3.17.3.tar.gz (1.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Collecting setuptools
        Downloading https://pypi.tuna.tsinghua.edu.cn/packages/47/6a/dfaf9838b6dd1f04537c0a66cf880dd24acd829f8a39d468c11fc0b7d8c6/setuptools-67.7.1-py3-none-any.whl (1.1 MB)
           ---------------------------------------- 1.1/1.1 MB 5.3 MB/s eta 0:00:00
      Collecting cython==3.0.0a11
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b6/50/97fec65cbde210f6bf71db1970ce8f6461a0594c619b6c6834d03742f1bd/Cython-3.0.0a11-py2.py3-none-any.whl (1.1 MB)
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.4.0 (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.4.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Hhhhhhao** [comment]
> The error message is as follows： Using cached https://pypi.tuna.tsinghua.edu.cn/packages/75/5d/0de5877f6aa71678ccaa230058f802a9405f7f60d07a990e4a28a5771d97/aim-3.17.3.tar.gz (1.6 MB) Installing build dependencies ... error error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> [8 lines of output] Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple Collecting setuptools Downloading https://pypi.tuna.tsinghua.edu.cn/packages/47/6a/dfaf9838b6dd1f04537c0a66cf880dd24acd829f8a39d468c11fc0b7d8c6/setuptools-67.7.1-py3-none-any.whl (1.1 MB) ---------------------------------------- 1.1/1.1 MB 5.3 MB/s eta 0:00:00 Collecting cython==3.0.0a11 Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b6/50/97fec65cbde210f6bf71db1970ce8f6461a0594c619b6c6834d03742f1bd/Cython-3.0.0a11-py2.py3-none-any.whl (1.1 MB) ERROR: Could not find a version that satisfies the requirement aimrocks==0.4.0 (from versions: 0.2.0) ERROR: No matching distribution found for aimrocks==0.4.0 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

 I'm not quite sure about this issue since I don't have a. windows environment. Maybe try to google it or ask chatGPT :)

**Comment by jafer11** [comment]
> > Windows10怎么安装aim，我用pip install aim命令报错。错误信息如下：
> > 收集 使用存档的 aim-3.17.3.tar.gz (1.6 MB) Installing build dependencies ... error error: subprocess-exited-with-error
> > × 用于安装构建依赖项的 pip 子进程未成功运行。 │ 退出代码：1 ╰─> [6 lines of output] ERROR: Could not find a version that satisfy the requirement aimrocks==0.4.0 (from versions: 0.2.0) [输出结束] [输出结束]
> > 注意：此错误源于子程序，可能不是 pip 的问题。 错误：子程序因错误而退出
> > × 用于安装构造依赖项的 pip 子进程未成功运行。 │ 退出代码：1 ╰─> 输入见上。
> > 注意：此错误源自子进程，可能不是 pip 的问题。
> 
> 在windows环境下的pycharm中安装指定版本的aim==2.4.0，高于这个版本的都装不上

感谢大佬，安装成功了
